### ISSUE TITLE
An empty task name leads to a crash

### ISSUE THREAD

**Issue by turtschan** [xoxys/ansible-later#29]
```
---
- name:
  shell: /bin/true
```
An empty task name leads to a crash in ansible-later 2.7. Tested with Python 3.6 + Ansible 2.9 and Python 3.7 + Ansible 2.8.

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
result = (True, func(*args, **kwds))
File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
return list(map(*args))
File "/usr/local/lib/python3.7/site-packages/ansiblelater/__main__.py", line 79, in _review_wrapper
return candidate.review(settings, lines)
File "/usr/local/lib/python3.7/site-packages/ansiblelater/command/candidates.py", line 113, in review
result = standard.check(self, settings.config)
File "/usr/local/lib/python3.7/site-packages/ansiblelater/rules/ansiblefiles.py", line 68, in check_name_format
if not name[0].isupper():
TypeError: 'NoneType' object is not subscriptable
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/bin/ansible-later", line 10, in <module>
sys.exit(main())
File "/usr/local/lib/python3.7/site-packages/ansiblelater/__main__.py", line 65, in main
errors = (sum(p.map(_review_wrapper, tasks)))
File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 268, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
raise self._value
TypeError: 'NoneType' object is not subscriptable 
```

**Comment by xoxys** [comment]
Thanks for reporting. Nice catch! I will look into this.

**Comment by xoxys** [comment]
@turtschan should be fixed in master branch and latest docker image. Can you test it again?

**Comment by turtschan** [comment]
Thank you @xoxys this works for me.

**Comment by xoxys** [comment]
Thanks for testing. I will prepare a release the next days.
