### ISSUE TITLE
Error while vault file classification if file is a binary

### ISSUE THREAD

**Issue by xoxys** [xoxys/ansible-later#6]
```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-later", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/ansiblelater/__main__.py", line 61, in main
    candidate = classify(filename)
  File "/usr/local/lib/python2.7/site-packages/ansiblelater/__init__.py", line 228, in classify
    return File(filename)
  File "/usr/local/lib/python2.7/site-packages/ansiblelater/__init__.py", line 111, in __init__
    super(RoleFile, self).__init__(filename)
  File "/usr/local/lib/python2.7/site-packages/ansiblelater/__init__.py", line 93, in __init__
    if f.readline().startswith("$ANSIBLE_VAULT"):
  File "/usr/local/lib/python2.7/codecs.py", line 692, in readline
    return self.reader.readline(size)
  File "/usr/local/lib/python2.7/codecs.py", line 547, in readline
    data = self.read(readsize, firstline=True)
  File "/usr/local/lib/python2.7/codecs.py", line 494, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 25: invalid start byte
```

**Comment by xoxys** [comment]
Fixed by 86ffffd8e1539d0f521c714cd3a51605851f6997
